#include "stdint.h"
struct pcie_value_desc{
	uint32_t value;
	char *desc;
};
struct pcie_dfx_info{
	char *desc1;
	char *desc2;
    char *base_desc;
	uint64_t base_addr;
	uint32_t offset;
	uint32_t bit_offset;
	uint32_t bit_width;
	int value_count;
	struct pcie_value_desc value_desc[100];	
};

#define PCIE_DFS_COUNT 1
static struct pcie_dfx_info g_dfx_info[] = {
   {
       .desc1="PCIE模式RC/EP",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0xc,
       .bit_offset=16,
       .bit_width=1,
       .value_count=2,
       .value_desc[0]= {
           .value=0,
           .desc=" rc",
                       },
       .value_desc[1]= {
           .value=1,
           .desc=" ep,
                       },
   },
   {
       .desc1="时钟来源",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x61c,
       .bit_offset=0,
       .bit_width=1,
       .value_count=2,
       .value_desc[0]= {
           .value=1’b1,
           .desc="单端时钟",
                       },
       .value_desc[1]= {
           .value=1‘b0,
           .desc="差分时钟,
                       },
   },
   {
       .desc1="时钟来源（频率）",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x604,
       .bit_offset=0,
       .bit_width=2,
       .value_count=2,
       .value_desc[0]= {
           .value=2'b00,
           .desc="24M",
                       },
       .value_desc[1]= {
           .value=2'b10,
           .desc="100M,
                       },
   },
   {
       .desc1="negotiate_speed",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x10,
       .bit_offset=22,
       .bit_width=2,
       .value_count=4,
       .value_desc[0]= {
           .value=2’b11,
           .desc="保留",
                       },
       .value_desc[1]= {
           .value=2’b10,
           .desc="8Gbps",
                       },
       .value_desc[2]= {
           .value=2’b01,
           .desc="5Gbps",
                       },
       .value_desc[3]= {
           .value=2’b00,
           .desc="2.5Gbps,
                       },
   },
   {
       .desc1="negotiate_width",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x10,
       .bit_offset=1,
       .bit_width=2,
       .value_count=3,
       .value_desc[0]= {
           .value=其他,
           .desc="保留",
                       },
       .value_desc[1]= {
           .value=2’b01,
           .desc="链路宽度为x2",
                       },
       .value_desc[2]= {
           .value=2’b00,
           .desc="链路宽度为x1,
                       },
   },
   {
       .desc1="支持的最高速率",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x0,
       .bit_offset=8,
       .bit_width=2,
       .value_count=3,
       .value_desc[0]= {
           .value=2’b10,
           .desc="pcie gen3模式",
                       },
       .value_desc[1]= {
           .value=2’b01,
           .desc="pcie gen2模式",
                       },
       .value_desc[2]= {
           .value=2’b00,
           .desc="pcie gen1模式,
                       },
   },
   {
       .desc1="支持的最大宽度",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x0,
       .bit_offset=5,
       .bit_width=2,
       .value_count=4,
       .value_desc[0]= {
           .value=2’b11,
           .desc="reserve",
                       },
       .value_desc[1]= {
           .value=2’b10,
           .desc="pcie默认使用4条链路训练；",
                       },
       .value_desc[2]= {
           .value=2’b01,
           .desc="pcie默认使用2条链路训练；",
                       },
       .value_desc[3]= {
           .value=2’b00,
           .desc="pcie默认使用1条链路训练,
                       },
   },
   {
       .desc1="link status",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x10,
       .bit_offset=30,
       .bit_width=2,
       .value_count=4,
       .value_desc[0]= {
           .value=2'b11,
           .desc=" linktraing完成，进入L0",
                       },
       .value_desc[1]= {
           .value=2'b10,
           .desc=" 有link，在进行初始化",
                       },
       .value_desc[2]= {
           .value=2'b01,
           .desc="在进行link training",
                       },
       .value_desc[3]= {
           .value=2'b00,
           .desc=" 没有检测到对端设备,
                       },
   },
   {
       .desc1="boot寄存器配置是否符合预期bar0",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x0240,
       .bit_offset=0,
       .bit_width=8,
       .value_count=0,
       .desc2="None",
   },
   {
       .desc1="boot寄存器配置是否符合预期bar2",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x0240,
       .bit_offset=16,
       .bit_width=8,
       .value_count=0,
       .desc2="None",
   },
   {
       .desc1="boot寄存器配置是否符合预期bar4",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x0244,
       .bit_offset=0,
       .bit_width=8,
       .value_count=0,
       .desc2="None",
   },
   {
       .desc1="SRIS是否使能",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x0,
       .bit_offset=2,
       .bit_width=1,
       .value_count=2,
       .value_desc[0]= {
           .value=1’b1,
           .desc="sris使能；",
                       },
       .value_desc[1]= {
           .value=1’b0,
           .desc="sris禁止；,
                       },
   },
   {
       .desc1="各种错误状态寄存器",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x24,
       .bit_offset=8,
       .bit_width=8,
       .value_count=0,
       .desc2="非严重错误发生次数状态",
   },
   {
       .desc1="各种错误状态寄存器",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x24,
       .bit_offset=16,
       .bit_width=8,
       .value_count=0,
       .desc2="严重错误发生次数状态",
   },
   {
       .desc1="各种错误状态寄存器",
       .base_desc="PCIE_SIDE_BAND_BASE ",
       .base_addr=0x388000,
       .offset=0x24,
       .bit_offset=24,
       .bit_width=8,
       .value_count=0,
       .desc2="可修正错误发生次数状态",
   },
   {
       .desc1="lane error",
       .base_desc="PCIE_CTRL_PF_BASE",
       .base_addr=0x380000,
       .offset=0x308,
       .bit_offset=0,
       .bit_width=2,
       .value_count=2,
       .value_desc[0]= {
           .value=1'b,
           .desc="该lane上有error",
                       },
       .value_desc[1]= {
           .value=0‘b,
           .desc="该lane上没有error,
                       },
   },
   {
       .desc1="lcrc error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x214,
       .bit_offset=0,
       .bit_width=16,
       .value_count=0,
       .desc2="收到的有lcrc错误的TLP个数",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=0,
       .bit_width=1,
       .value_count=0,
       .desc2="PNP接收buffer中读数据奇偶校验错误",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=1,
       .bit_width=1,
       .value_count=0,
       .desc2="completion接收FIFO中读数据奇偶校验错误",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=2,
       .bit_width=1,
       .value_count=0,
       .desc2="replay buffer中读数据奇偶校验错误",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=3,
       .bit_width=1,
       .value_count=0,
       .desc2="PNP接收buffer出现overflow",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=4,
       .bit_width=1,
       .value_count=0,
       .desc2="completion接收FIFO出现overflow",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=5,
       .bit_width=1,
       .value_count=0,
       .desc2="replay buffer timed out",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=6,
       .bit_width=1,
       .value_count=0,
       .desc2="同一个TLP重传4次之后replay timer rolled over",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=7,
       .bit_width=1,
       .value_count=0,
       .desc2="接收端检测到physical layer err，也就是通常说的rx err",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=8,
       .bit_width=1,
       .value_count=0,
       .desc2="malformed TLP received from the link",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=9,
       .bit_width=1,
       .value_count=0,
       .desc2="Unexpected Completion received from the link.",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=10,
       .bit_width=1,
       .value_count=0,
       .desc2="An error was observed in the flow control advertisements from the other side.",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=11,
       .bit_width=1,
       .value_count=0,
       .desc2="completion timeout",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=26,
       .bit_width=1,
       .value_count=0,
       .desc2="DMA outbound buffer uncorrectable error",
   },
   {
       .desc1="Local error",
       .base_desc="PCIE_CTRL_LOCAL_BASE ",
       .base_addr=0x385000,
       .offset=0x20C,
       .bit_offset=27,
       .bit_width=1,
       .value_count=0,
       .desc2="DMA inbound buffer uncorrectable error",
   },
};
